"""Regenerate this repository's root .editorconfig from the shipped configs.

The repository's own projects build with plain Microsoft.NET.Sdk, so they never receive the
injected Headless.NET.Sdk.*.editorconfig files. The root .editorconfig therefore carries the
editor-only scaffold plus the injected analyzer settings, generated here so it cannot drift.
AnalyzerRuleCoverageTests.root_editorconfig_should_match_the_injected_configs checks the result.

Usage: python3 eng/tools/sync_root_editorconfig.py
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CONFIGS = ROOT / "src" / "Headless.NET.Sdk" / "configurations"

HEADER = """##########################################
# headless-sdk repository settings
#
# Generated by eng/tools/sync_root_editorconfig.py; do not edit by hand. Edit the shipped configs
# under src/Headless.NET.Sdk/configurations and run the script again.
#
# Editor settings come from the editorconfig.txt scaffold. This repository's own projects build
# with plain Microsoft.NET.Sdk and never receive the injected Headless.NET.Sdk.*.editorconfig
# files, so their analyzer settings are repeated in the sections at the end.
##########################################
"""


def body(path: Path) -> str:
    """Drop the global-config keys and the file's own header comment, keep everything after it."""
    lines = path.read_text().split("\n")
    lines = [l for l in lines if not l.startswith(("is_global", "global_level"))]
    start = next(i for i, l in enumerate(lines) if l.startswith("####"))
    return "\n".join(lines[start:]).strip("\n")


def scaffold() -> str:
    """The editorconfig.txt content after its own scaffold-specific banner."""
    text = (CONFIGS / "editorconfig.txt").read_text()
    banner_end = text.index("##########################################\n", 1) + len("##########################################\n")
    return text[banner_end:].strip("\n")


def render() -> str:
    parts = [
        HEADER,
        scaffold(),
        "",
        "##########################################",
        "# Injected analyzer settings: Headless.NET.Sdk.Analyzers.editorconfig",
        "##########################################",
        "",
        "[*.cs]",
        "",
        body(CONFIGS / "Headless.NET.Sdk.Analyzers.editorconfig"),
        "",
        "##########################################",
        "# Injected test-project overlay: Headless.NET.Sdk.Tests.editorconfig",
        "##########################################",
        "",
        "[tests/**/*.cs]",
        "",
        body(CONFIGS / "Headless.NET.Sdk.Tests.editorconfig"),
        "",
    ]
    return "\n".join(parts)


if __name__ == "__main__":
    (ROOT / ".editorconfig").write_text(render())
    print("wrote .editorconfig")
